version: '3'

services:
  registry:
    restart: always
    image: registry:2
    container_name: registry-srv
    ports:
      - 5000:5000
    volumes:
      - ./conf/registry-config-srv.yml:/etc/docker/registry/config.yml
      - ./data:/var/lib/registry
      - ./certs:/certs
      - ./auth:/auth

