version: 0.1
log:
  accesslog:
    disabled: true
  level: warn
  formatter: text
  fields:
    service: registry
    environment: staging
storage:
  filesystem:
    rootdirectory: /var/lib/registry
    maxthreads: 100
  delete:
    enabled: true
  cache:
    blobdescriptor: inmemory
  maintenance:
    uploadpurging:
      enabled: true
      age: 36h
      interval: 4h
      dryrun: false
    readonly:
      enabled: false
auth:
  htpasswd:
    realm: Registry Realm
    path: /auth/htpasswd
http:
  addr: localhost:5000
  host: https://registry.jeph.tech:5000
  tls:
    certificate: /certs/domain.crt
    key: /certs/domain.key

